import { ColumnConfig } from '@tressi/shared/ui';

import { ColumnKey } from './column-keys.enum';

export const DEFAULT_COLUMN_CONFIGS: ColumnConfig[] = [
  // Fixed columns (non-draggable) - always visible
  {
    key: ColumnKey.SELECT,
    label: 'Select',
    field: 'select',
    visible: true,
    group: 'basic',
    order: 0,
    draggable: false,
    width: 50,
  },
  {
    key: ColumnKey.STATUS,
    label: 'Status',
    field: 'test.status',
    visible: true,
    group: 'basic',
    order: 1,
    draggable: false,
    sortable: true,
    width: 100,
  },
  // Basic test information
  {
    key: ColumnKey.START_TIME,
    label: 'Start Time',
    field: 'summary.global.epochStartedAt',
    format: 'datetime',
    visible: true,
    group: 'basic',
    order: 2,
    draggable: true,
    sortable: true,
    width: 180,
  },
  {
    key: ColumnKey.END_TIME,
    label: 'End Time',
    field: 'summary.global.epochEndedAt',
    format: 'datetime',
    visible: false,
    group: 'basic',
    order: 3,
    draggable: true,
    sortable: true,
    width: 180,
  },
  {
    key: ColumnKey.DURATION,
    label: 'Duration',
    field: 'test.duration',
    format: 'duration',
    visible: true,
    group: 'basic',
    order: 4,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.TRESSI_VERSION,
    label: 'Version',
    field: 'summary.tressiVersion',
    visible: false,
    group: 'basic',
    order: 13,
    draggable: true,
    sortable: true,
    width: 100,
  },
  // Request metrics
  {
    key: ColumnKey.TOTAL_REQUESTS,
    label: 'Total',
    field: 'summary.global.totalRequests',
    format: 'number',
    visible: true,
    group: 'request',
    order: 5,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.SUCCESSFUL_REQUESTS,
    label: 'Successful',
    field: 'summary.global.successfulRequests',
    format: 'number',
    visible: false,
    group: 'request',
    order: 6,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.FAILED_REQUESTS,
    label: 'Failed',
    field: 'summary.global.failedRequests',
    format: 'number',
    visible: false,
    group: 'request',
    order: 7,
    draggable: true,
    sortable: true,
    width: 100,
  },
  // Latency metrics (grouped together from min to max)
  {
    key: ColumnKey.MIN_LATENCY,
    label: 'Min Latency',
    field: 'summary.global.minLatencyMs',
    format: 'milliseconds',
    visible: false,
    group: 'latency',
    order: 8,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.p50_LATENCY,
    label: 'P50 Latency',
    field: 'summary.global.p50LatencyMs',
    format: 'milliseconds',
    visible: false,
    group: 'latency',
    order: 9,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.P95_LATENCY,
    label: 'P95 Latency',
    field: 'summary.global.p95LatencyMs',
    format: 'milliseconds',
    visible: false,
    group: 'latency',
    order: 10,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.P99_LATENCY,
    label: 'P99 Latency',
    field: 'summary.global.p99LatencyMs',
    format: 'milliseconds',
    visible: false,
    group: 'latency',
    order: 11,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.MAX_LATENCY,
    label: 'Max Latency',
    field: 'summary.global.maxLatencyMs',
    format: 'milliseconds',
    visible: false,
    group: 'latency',
    order: 12,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.NETWORK_BYTES_SENT,
    label: 'Bytes Sent',
    field: 'summary.global.networkBytesSent',
    format: 'bytes',
    visible: false,
    group: 'network',
    order: 14,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.NETWORK_BYTES_RECEIVED,
    label: 'Bytes Received',
    field: 'summary.global.networkBytesReceived',
    format: 'bytes',
    visible: false,
    group: 'network',
    order: 15,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.NETWORK_THROUGHPUT,
    label: 'Network Throughput',
    field: 'summary.global.networkBytesPerSec',
    format: 'bytesPerSec',
    visible: false,
    group: 'network',
    order: 16,
    draggable: true,
    sortable: true,
    width: 140,
  },
  {
    key: ColumnKey.ERROR_RATE,
    label: 'Error Rate',
    field: 'summary.global.errorRate',
    format: 'percentage',
    visible: true,
    group: 'performance',
    order: 17,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.AVG_RPS,
    label: 'Avg RPS',
    field: 'summary.global.averageRequestsPerSecond',
    format: 'number',
    visible: false,
    group: 'performance',
    order: 18,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.PEAK_RPS,
    label: 'Peak RPS',
    field: 'summary.global.peakRequestsPerSecond',
    format: 'number',
    visible: false,
    group: 'performance',
    order: 19,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.FINAL_DURATION_SEC,
    label: 'Duration',
    field: 'summary.global.finalDurationSec',
    format: 'duration',
    visible: false,
    group: 'performance',
    order: 20,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.CONFIG_DURATION,
    label: 'Config Duration',
    field: 'summary.configSnapshot.options.durationSec',
    format: 'duration',
    visible: false,
    group: 'configuration',
    order: 25,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.WORKER_THREADS,
    label: 'Worker Threads',
    field: 'summary.configSnapshot.options.threads',
    format: 'number',
    visible: false,
    group: 'configuration',
    order: 26,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.WORKER_MEMORY_LIMIT,
    label: 'Memory Limit',
    field: 'summary.configSnapshot.options.workerMemoryLimit',
    format: 'bytes',
    visible: false,
    group: 'configuration',
    order: 27,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.GLOBAL_RAMP_UP,
    label: 'Ramp Up',
    field: 'summary.configSnapshot.options.rampUpDurationSec',
    format: 'duration',
    visible: false,
    group: 'configuration',
    order: 29,
    draggable: true,
    sortable: true,
    width: 120,
  },
];
