import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { logger } from 'hono/logger';

import { globalEventEmitter } from '../events/global-event-emitter';
import { terminal } from '../tui/terminal';
import { registerRoutes } from './routes';
import { SSEManager } from './utils/sse-manager';

/**
 * TressiServer - A simple Hono server for the tressi serve command
 */
export class TressiServer {
  private app: Hono;
  private server: ReturnType<typeof serve> | null = null;
  private port: number;
  private sseManager: SSEManager;

  constructor(port: number = 3108) {
    this.port = port;
    this.app = new Hono();
    this.sseManager = new SSEManager();

    this.setupMiddleware();
    this.setupRoutes();
    this.setupMetricsListener();
  }

  /**
   * Sets up HTTP middleware for the Hono server.
   *
   * @remarks
   * Configures essential middleware including:
   * - Request logging using Hono's built-in logger
   * - CORS with specific origins (localhost server and Angular dev server)
   * - Credentials and method allowances for API access
   * - Preflight request caching for performance
   *
   * The middleware stack is ordered with logging first to capture all requests,
   * followed by CORS to handle cross-origin requests from the web UI.
   */
  private setupMiddleware(): void {
    // Add logger middleware first to log all requests
    this.app.use(logger());

    this.app.use(
      '*',
      cors({
        origin: [
          `http://localhost:${this.port}`, // The server itself (localhost:3108)
          'http://localhost:4200', // Angular development server
        ],
        credentials: true,
        allowMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
        allowHeaders: ['Content-Type', 'Authorization'],
        maxAge: 600, // Cache preflight requests for 10 minutes
      }),
    );
  }

  /**
   * Registers application routes with the Hono server.
   *
   * @remarks
   * Delegates route registration to the centralized routes module.
   * This separation keeps the server class focused on lifecycle management
   * while route definitions are maintained separately for better organization.
   */
  private setupRoutes(): void {
    registerRoutes(this.app, this.sseManager);
  }

  /**
   * Sets up event listener for real-time metrics broadcasting.
   *
   * @remarks
   * Listens for 'metrics' events from the global event emitter and broadcasts
   * them to all connected SSE clients. This enables real-time metrics streaming
   * to the web UI without requiring polling.
   *
   * The listener remains active for the server's lifetime, automatically
   * forwarding metrics as they are generated by the metrics aggregator.
   */
  private setupMetricsListener(): void {
    globalEventEmitter.on('metrics', (metrics) => {
      this.sseManager.broadcast(metrics);
    });
  }

  /**
   * Starts the Tressi server and begins listening for connections.
   *
   * @returns Promise that resolves when the server is successfully listening
   *
   * @remarks
   * Initializes the Hono server with the configured middleware and routes.
   * Returns a promise that resolves when the server is ready to accept connections.
   *
   * Logs startup information including the server URL and health check endpoint.
   * Rejects the promise if server startup fails for any reason.
   *
   * @throws {Error} If server startup fails due to port conflicts or other issues
   */
  async start(): Promise<void> {
    return new Promise((resolve, reject) => {
      try {
        this.server = serve({
          fetch: this.app.fetch,
          port: this.port,
        });

        this.server.on('listening', () => {
          terminal.print(
            `🚀 Tressi server is running on http://localhost:${this.port}`,
          );
          terminal.print(
            `📊 Health check available at http://localhost:${this.port}/health`,
          );
          resolve();
        });

        this.server.on('error', (error) => {
          reject(error as Error);
        });
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Stops the Tressi server and cleans up resources.
   *
   * @returns Promise that resolves when the server is fully stopped
   *
   * @remarks
   * Performs graceful shutdown by:
   * 1. Closing the HTTP server to stop accepting new connections
   * 2. Cleaning up SSE client connections
   * 3. Logging shutdown confirmation
   *
   * Returns immediately if the server is not running. The cleanup process
   * ensures that all resources are properly released and clients are notified
   * of the disconnection.
   */
  async stop(): Promise<void> {
    return new Promise((resolve) => {
      if (this.server) {
        this.server.close(() => {
          this.sseManager.cleanup();
          terminal.print('\n🛑 Tressi server stopped');
          resolve();
        });
      } else {
        resolve();
      }
    });
  }
}
