/**
 * Icon names for shared use across UI components
 */

/**
 * Type representing the names of available icons.
 */
export type IconName =
  | 'add'
  | 'analytics'
  | 'arrow_back'
  | 'autorenew'
  | 'bar_chart'
  | 'browse_activity'
  | 'check'
  | 'check_circle'
  | 'chevron_left'
  | 'chevron_right'
  | 'close'
  | 'copy_all'
  | 'delete'
  | 'donut_large'
  | 'drag_indicator'
  | 'drag_pan'
  | 'dynamic_form'
  | 'edit_square'
  | 'edit'
  | 'error'
  | 'expand_all'
  | 'file_save'
  | 'health_and_safety'
  | 'help_outline'
  | 'inbox'
  | 'info'
  | 'keyboard_arrow_down'
  | 'keyboard_arrow_up'
  | 'lan'
  | 'light_mode'
  | 'list_alt'
  | 'menu'
  | 'memory'
  | 'network_check'
  | 'palette'
  | 'play_circle'
  | 'post_add'
  | 'reset_focus'
  | 'rocket'
  | 'save_as'
  | 'schedule'
  | 'sdk'
  | 'search'
  | 'select'
  | 'send'
  | 'speed'
  | 'stat_1'
  | 'stat_2'
  | 'stat_3'
  | 'tag'
  | 'text_snippet'
  | 'thunderstorm'
  | 'timer'
  | 'tune'
  | 'upload_file'
  | 'view_column'
  | 'warning'
  | 'zoom_in'
  | 'zoom_out';
