export enum ColumnKey {
  SELECT = 'select',
  STATUS = 'status',
  START_TIME = 'startTime',
  ID = 'id',
  DURATION = 'duration',
  TOTAL_REQUESTS = 'totalRequests',
  ERROR_RATE = 'errorRate',
  SUCCESSFUL_REQUESTS = 'successfulRequests',
  FAILED_REQUESTS = 'failedRequests',
  AVG_LATENCY = 'avgLatency',
  P95_LATENCY = 'p95Latency',
  P99_LATENCY = 'p99Latency',
  ACTUAL_RPS = 'actualRps',
  ACHIEVED_PERCENTAGE = 'achievedPercentage',
  TRESSI_VERSION = 'tressiVersion',
  MIN_LATENCY = 'minLatency',
  MAX_LATENCY = 'maxLatency',
  THEORETICAL_MAX_RPS = 'theoreticalMaxRps',
}
