import { ColumnKey } from './column-keys.enum';
import { ColumnConfig } from './test-list-columns.service';

export const DEFAULT_COLUMN_CONFIGS: ColumnConfig[] = [
  // Fixed columns (non-draggable)
  {
    key: ColumnKey.SELECT,
    label: 'Select',
    field: 'select',
    visible: true,
    group: 'basic',
    order: 0,
    draggable: false,
    width: 50,
  },
  {
    key: ColumnKey.STATUS,
    label: 'Status',
    field: 'test.status',
    visible: true,
    group: 'basic',
    order: 1,
    draggable: false,
    sortable: true,
    width: 100,
  },
  // Draggable columns with sequential order values
  {
    key: ColumnKey.START_TIME,
    label: 'Start Time',
    field: 'test.epochStartedAt',
    format: 'datetime',
    visible: true,
    group: 'basic',
    order: 2,
    draggable: true,
    sortable: true,
    width: 180,
  },
  {
    key: ColumnKey.ID,
    label: 'Test ID',
    field: 'test.id',
    visible: false,
    group: 'basic',
    order: 3,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.DURATION,
    label: 'Duration',
    field: 'test.duration',
    format: 'duration',
    visible: true,
    group: 'basic',
    order: 4,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.REQUESTS,
    label: 'Requests',
    field: 'summary.global.totalRequests',
    format: 'number',
    visible: true,
    group: 'basic',
    order: 5,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.ERROR_RATE,
    label: 'Error Rate',
    field: 'summary.global.errorPercentage',
    format: 'percentage',
    visible: false,
    group: 'basic',
    order: 6,
    draggable: true,
    sortable: true,
    width: 100,
  },

  // Performance columns (optional)
  {
    key: ColumnKey.SUCCESSFUL_REQUESTS,
    label: 'Successful',
    field: 'summary.global.successfulRequests',
    format: 'number',
    visible: false,
    group: 'performance',
    order: 7,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.FAILED_REQUESTS,
    label: 'Failed',
    field: 'summary.global.failedRequests',
    format: 'number',
    visible: false,
    group: 'performance',
    order: 8,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.AVG_LATENCY,
    label: 'Avg Latency',
    field: 'summary.global.averageLatency',
    format: 'milliseconds',
    visible: false,
    group: 'performance',
    order: 9,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.P95_LATENCY,
    label: 'P95 Latency',
    field: 'summary.global.p95Latency',
    format: 'milliseconds',
    visible: false,
    group: 'performance',
    order: 10,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.P99_LATENCY,
    label: 'P99 Latency',
    field: 'summary.global.p99Latency',
    format: 'milliseconds',
    visible: false,
    group: 'performance',
    order: 11,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.ACTUAL_RPS,
    label: 'Actual RPS',
    field: 'summary.global.requestsPerSecond',
    format: 'number',
    visible: false,
    group: 'performance',
    order: 12,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.ACHIEVED_PERCENTAGE,
    label: 'Achieved %',
    field: 'summary.global.achievedPercentage',
    format: 'percentage',
    visible: false,
    group: 'performance',
    order: 13,
    draggable: true,
    sortable: true,
    width: 100,
  },

  // Advanced columns
  {
    key: ColumnKey.TRESSI_VERSION,
    label: 'Version',
    field: 'summary.tressiVersion',
    visible: false,
    group: 'advanced',
    order: 14,
    draggable: true,
    sortable: true,
    width: 100,
  },
  {
    key: ColumnKey.MIN_LATENCY,
    label: 'Min Latency',
    field: 'summary.global.minLatency',
    format: 'milliseconds',
    visible: false,
    group: 'advanced',
    order: 15,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.MAX_LATENCY,
    label: 'Max Latency',
    field: 'summary.global.maxLatency',
    format: 'milliseconds',
    visible: false,
    group: 'advanced',
    order: 16,
    draggable: true,
    sortable: true,
    width: 120,
  },
  {
    key: ColumnKey.THEORETICAL_MAX_RPS,
    label: 'Max RPS',
    field: 'summary.global.theoreticalMaxRps',
    format: 'number',
    visible: false,
    group: 'advanced',
    order: 17,
    draggable: true,
    sortable: true,
    width: 100,
  },
];
