import { ColumnConfig } from './test-list-columns.service';

export const DEFAULT_COLUMN_CONFIGS: ColumnConfig[] = [
  // Fixed columns (non-draggable)
  {
    key: 'select',
    label: 'Select',
    field: 'select',
    visible: true,
    group: 'basic',
    order: 0,
    draggable: false,
  },
  {
    key: 'status',
    label: 'Status',
    field: 'test.status',
    visible: true,
    group: 'basic',
    order: 1,
    draggable: false,
  },
  // Draggable columns with sequential order values
  {
    key: 'startTime',
    label: 'Start Time',
    field: 'test.epochStartedAt',
    format: 'datetime',
    visible: true,
    group: 'basic',
    order: 2,
    draggable: true,
  },
  {
    key: 'id',
    label: 'Test ID',
    field: 'test.id',
    visible: false,
    group: 'basic',
    order: 3,
    draggable: true,
  },
  {
    key: 'duration',
    label: 'Duration',
    field: 'test.duration',
    format: 'duration',
    visible: true,
    group: 'basic',
    order: 4,
    draggable: true,
  },
  {
    key: 'requests',
    label: 'Requests',
    field: 'summary.global.totalRequests',
    format: 'number',
    visible: true,
    group: 'basic',
    order: 4,
    draggable: true,
  },
  {
    key: 'errorRate',
    label: 'Error Rate',
    field: 'summary.global.errorRate',
    format: 'percentage',
    visible: false,
    group: 'basic',
    order: 5,
    draggable: true,
  },

  // Performance columns (optional)
  {
    key: 'successfulRequests',
    label: 'Successful',
    field: 'summary.global.successfulRequests',
    format: 'number',
    visible: false,
    group: 'performance',
    order: 6,
    draggable: true,
  },
  {
    key: 'failedRequests',
    label: 'Failed',
    field: 'summary.global.failedRequests',
    format: 'number',
    visible: false,
    group: 'performance',
    order: 7,
    draggable: true,
  },
  {
    key: 'avgLatency',
    label: 'Avg Latency',
    field: 'summary.global.averageLatency',
    format: 'milliseconds',
    visible: false,
    group: 'performance',
    order: 8,
    draggable: true,
  },
  {
    key: 'p95Latency',
    label: 'P95 Latency',
    field: 'summary.global.p95Latency',
    format: 'milliseconds',
    visible: false,
    group: 'performance',
    order: 9,
    draggable: true,
  },
  {
    key: 'p99Latency',
    label: 'P99 Latency',
    field: 'summary.global.p99Latency',
    format: 'milliseconds',
    visible: false,
    group: 'performance',
    order: 10,
    draggable: true,
  },
  {
    key: 'actualRps',
    label: 'Actual RPS',
    field: 'summary.global.requestsPerSecond',
    format: 'number',
    visible: false,
    group: 'performance',
    order: 11,
    draggable: true,
  },
  {
    key: 'achievedPercentage',
    label: 'Achieved %',
    field: 'summary.global.achievedPercentage',
    format: 'percentage',
    visible: false,
    group: 'performance',
    order: 12,
    draggable: true,
  },

  // Advanced columns
  {
    key: 'tressiVersion',
    label: 'Version',
    field: 'summary.tressiVersion',
    visible: false,
    group: 'advanced',
    order: 13,
    draggable: true,
  },
  {
    key: 'minLatency',
    label: 'Min Latency',
    field: 'summary.global.minLatency',
    format: 'milliseconds',
    visible: false,
    group: 'advanced',
    order: 14,
    draggable: true,
  },
  {
    key: 'maxLatency',
    label: 'Max Latency',
    field: 'summary.global.maxLatency',
    format: 'milliseconds',
    visible: false,
    group: 'advanced',
    order: 15,
    draggable: true,
  },
  {
    key: 'theoreticalMaxRps',
    label: 'Max RPS',
    field: 'summary.global.theoreticalMaxRps',
    format: 'number',
    visible: false,
    group: 'advanced',
    order: 16,
    draggable: true,
  },
];
